:set fileencodings=utf-8,cp932,euc-jp,sjis
:set encoding=utf-8
:set fileformat=unix

set number
set title
set tabstop=4
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set expandtab
set nrformats-=octal
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start
set wildmenu
set cursorline
set showmatch 
set hlsearch
set ignorecase
set smartcase
set wrapscan
set noerrorbells
